import os
import random
from pyuvm import uvm_sequence
from tb.hybrid.ml_pool import MLTestPool

from tb.sequences.sequence_item import (
    AXISeqItem,
    VALID_REGS,
    ADDR_CATEGORIES,
    random_invalid_addr,
    random_data_value,
)

from tb.components.env import (
    get_uncovered_bins,
    coverage_complete,
    TOTAL_BINS,
)


class AXISequence(uvm_sequence):
    """
    Hybrid AXI4-Lite sequence.

    Two modes:

    1. Baseline (use_hybrid=False)
       - Pure constrained-random generation.

    2. Hybrid mode (use_hybrid=True)
       - Replay clustered testcases generated by
         train_model.py + cluster_tests.py.
    """

    def __init__(
        self,
        name="AXISequence",
        total_budget=300,
        use_hybrid=False,
    ):
        super().__init__(name)

        self.total_budget = total_budget
        self.use_hybrid = use_hybrid

        # Shared execution counter across both phases
        self.executed = 0

    # ==========================================================
    # Baseline generation
    # ==========================================================

    async def run_baseline(self):

        print(f"[BASELINE MODE] Running {self.total_budget} random tests")

        for _ in range(self.total_budget):

            item = AXISeqItem("item")
            item.randomize()

            await self.start_item(item)
            await self.finish_item(item)

            self.executed += 1

    # ==========================================================
    # ML replay mode
    # ==========================================================

    async def run_ml_pool(self):

        print("AXI Hybrid Sequence Started")

        # Replay clustered testcases from clustered_tests.csv.

        base_dir = os.path.dirname(__file__)

        csv_path = os.path.join(
            base_dir,
            "../../ml/clustered_tests.csv",
        )

        pool = MLTestPool(csv_path)

        remaining_budget = self.total_budget - self.executed

        tests_to_run = min(
            len(pool),
            remaining_budget,
        )

        print(f"[HYBRID MODE] Running {tests_to_run} clustered testcases")

        reverse_txn_map = {
            0: "WRITE",
            1: "READ",
        }

        reverse_addr_map = {
            0: "REG0",
            1: "REG1",
            2: "REG2",
            3: "REG3",
            4: "INVALID",
        }

        reverse_data_map = {
            0: "ZERO",
            1: "SMALL",
            2: "LARGE",
            3: "NA",
        }

        for testcase in pool.get_all()[:tests_to_run]:

            if self.executed >= self.total_budget:
                break

            if coverage_complete():
                break

            txn_type = reverse_txn_map[testcase["txn_type"]]
            addr_cat = reverse_addr_map[testcase["addr_category"]]
            data_label = reverse_data_map[testcase["data_type"]]

            item = AXISeqItem("item")

            item.txn_type = txn_type

            # -----------------------------
            # Address
            # -----------------------------
            if addr_cat == "INVALID":
                item.addr = random_invalid_addr()
            else:
                item.addr = VALID_REGS[
                    ADDR_CATEGORIES.index(addr_cat)
                ]

            # -----------------------------
            # Data
            # -----------------------------
            if txn_type == "WRITE":

                if addr_cat == "INVALID":

                    item.data_type = "NA"
                    item.wdata = random.randint(
                        0,
                        0xFFFFFFFF,
                    )

                else:

                    item.data_type = data_label

                    item.wdata = random_data_value(
                        data_label
                    )

            else:

                item.data_type = "NA"
                item.wdata = 0

            await self.start_item(item)
            await self.finish_item(item)

            self.executed += 1
        print(
            f"[HYBRID MODE] Replay complete "
            f"({self.executed}/{self.total_budget})"
        )

    # ==========================================================
    # Directed testcase generation
    # ==========================================================

    def generate_directed_item(self, uncovered_bin):       
       

        item = AXISeqItem("item")

        # READ bin
        if uncovered_bin[0] == "READ":

            _, addr_cat = uncovered_bin

            item.txn_type = "READ"

            if addr_cat == "INVALID":
                item.addr = random_invalid_addr()
            else:
                item.addr = VALID_REGS[
                    ADDR_CATEGORIES.index(addr_cat)
                ]

            item.wdata = 0
            item.data_type = "NA"

            return item

        # WRITE bin
        if uncovered_bin[0] == "WRITE":

            _, addr_cat, data_type = uncovered_bin

            item.txn_type = "WRITE"

            if addr_cat == "INVALID":
                item.addr = random_invalid_addr()
                item.wdata = random.randint(0, 0xFFFFFFFF)
                item.data_type = "NA"

            else:
                item.addr = VALID_REGS[
                    ADDR_CATEGORIES.index(addr_cat)
                ]

                item.data_type = data_type
                item.wdata = random_data_value(data_type)

            return item

        return None

    # ==========================================================
    # Gap filling phase
    # ==========================================================

    async def run_gap_fill(self):

        print("[HYBRID MODE] Starting deterministic gap filling")

        while (
            self.executed < self.total_budget
            and not coverage_complete()
        ):

            uncovered = get_uncovered_bins()

            if not uncovered:
                break

            target_bin = uncovered.pop()

            # ---------------------------------
            # RAW bin
            # ---------------------------------
            if target_bin[0] == "RAW":

                reg = target_bin[1]
                addr = VALID_REGS[
                    ADDR_CATEGORIES.index(reg)
                ]

                # WRITE transaction
                w = AXISeqItem("item")
                w.txn_type = "WRITE"
                w.addr = addr
                w.data_type = "SMALL"
                w.wdata = random_data_value("SMALL")

                await self.start_item(w)
                await self.finish_item(w)
                self.executed += 1

                if self.executed >= self.total_budget:
                    break

                # READ transaction
                r = AXISeqItem("item")
                r.txn_type = "READ"
                r.addr = addr
                r.wdata = 0
                r.data_type = "NA"

                await self.start_item(r)
                await self.finish_item(r)
                self.executed += 1

                continue

            # ---------------------------------
            # DOUBLE WRITE bin
            # ---------------------------------
            if target_bin[0] == "DOUBLE_WRITE":

                reg = target_bin[1]
                addr = VALID_REGS[
                    ADDR_CATEGORIES.index(reg)
                ]

                for _ in range(2):

                    if self.executed >= self.total_budget:
                        break

                    w = AXISeqItem("item")
                    w.txn_type = "WRITE"
                    w.addr = addr
                    w.data_type = "SMALL"
                    w.wdata = random_data_value("SMALL")

                    await self.start_item(w)
                    await self.finish_item(w)

                    self.executed += 1

                continue

            # ---------------------------------
            # Existing READ / WRITE bins
            # ---------------------------------
            item = self.generate_directed_item(target_bin)

            if item is None:
                continue

            await self.start_item(item)
            await self.finish_item(item)

            self.executed += 1

        print(
            f"[HYBRID MODE] Gap filling complete "
            f"({self.executed}/{self.total_budget})"
        )

    # ==========================================================
    # Main sequence body
    # ==========================================================

    async def body(self):

        print(">>> BODY ENTERED")

        print("===========================================")
        print("AXI Hybrid Sequence Started")
        print("===========================================")

        if self.use_hybrid:

            print("[HYBRID MODE] Enabled")

            await self.run_ml_pool()

            if (
                self.executed < self.total_budget
                and not coverage_complete()
            ):
                await self.run_gap_fill()

        else:

            print("[BASELINE MODE] Enabled")

            await self.run_baseline()

        print("===========================================")
        print("Sequence Finished")
        print(f"Executed Tests : {self.executed}")
        print(f"Coverage Goal  : {TOTAL_BINS} bins")
        print("===========================================")      