import os
import random
import pandas as pd

from pyuvm import uvm_sequence

from tb.sequences.sequence_item import (
    AXISeqItem,
    VALID_REGS,
    ADDR_CATEGORIES,
    random_invalid_addr,
    random_data_value,
)
from tb.hybrid.gap_analyzer import CoverageGapAnalyzer
from tb.hybrid.directed_generator import DirectedGenerator
from tb.hybrid.budget_manager import BudgetManager

from tb.components.env import (
    get_covered_bins,
    get_uncovered_bins,
    coverage_complete,
    TOTAL_BINS,
)

class AXISequence(uvm_sequence):
    """
    Offline AXI4-Lite sequence.

    Two modes:

    1. Baseline (use_ml=False)
       - Pure constrained-random generation.

    2. ML mode (use_ml=True)
       - Replay clustered testcases generated by
         train_model.py + cluster_tests.py.
    """

    def __init__(self, name="AXISequence", num_tests=300, use_ml=False):
        super().__init__(name)

        self.num_tests = num_tests
        self.use_ml = use_ml

    # ==========================================================
    # Baseline generation
    # ==========================================================

    async def run_baseline(self):

        print(f"[BASELINE MODE] Running {self.num_tests} random tests")

        for _ in range(self.num_tests):

            item = AXISeqItem("item")
            item.randomize()

            await self.start_item(item)
            await self.finish_item(item)

    # ==========================================================
    # ML replay mode
    # ==========================================================

    async def run_ml_pool(self):
        """
        Replay clustered testcases from clustered_tests.csv.
        """

        base_dir = os.path.dirname(__file__)

        csv_path = os.path.join(
            base_dir,
            "../../ml/clustered_tests.csv",
        )

        df = pd.read_csv(csv_path)

        print(f"[ML MODE] Running {len(df)} testcases")

        reverse_txn_map = {
            0: "WRITE",
            1: "READ",
        }

        reverse_addr_map = {
            0: "REG0",
            1: "REG1",
            2: "REG2",
            3: "REG3",
            4: "INVALID",
        }

        reverse_data_map = {
            0: "ZERO",
            1: "SMALL",
            2: "LARGE",
            3: "NA",
        }

        for _, row in df.iterrows():

            txn_type = reverse_txn_map[int(row["txn_type"])]
            addr_cat = reverse_addr_map[int(row["addr_category"])]
            data_label = reverse_data_map[int(row["data_type"])]

            item = AXISeqItem("item")

            item.txn_type = txn_type

            # -----------------------------
            # Address
            # -----------------------------
            if addr_cat == "INVALID":
                item.addr = random_invalid_addr()
            else:
                item.addr = VALID_REGS[
                    ADDR_CATEGORIES.index(addr_cat)
                ]

            # -----------------------------
            # Data
            # -----------------------------
            if txn_type == "WRITE":

                if addr_cat == "INVALID":

                    item.data_type = "NA"
                    item.wdata = random.randint(
                        0,
                        0xFFFFFFFF,
                    )

                else:

                    item.data_type = data_label

                    item.wdata = random_data_value(
                        data_label
                    )

            else:
                item.data_type = "NA"
                item.wdata = 0

            await self.start_item(item)
            await self.finish_item(item)

        print("[ML MODE] Done.")
        
            # ==========================================================
    # Hybrid Gap Filling
    # ==========================================================

    async def run_gap_fill(self):
        """
        Execute deterministic directed transactions for all
        uncovered coverage bins until coverage is complete or
        the execution budget is exhausted.
        """

        analyzer = CoverageGapAnalyzer(TOTAL_BINS)
        generator = DirectedGenerator()
        budget = BudgetManager()

        print("[HYBRID] Starting deterministic gap filling...")

        while True:

            covered = get_covered_bins()

            if analyzer.coverage_complete(covered):
                print("[HYBRID] Functional coverage complete.")
                break

            if budget.exhausted():
                print("[HYBRID] Budget exhausted.")
                break

            uncovered = list(get_uncovered_bins())

            if not uncovered:
                print("[HYBRID] No uncovered bins remain.")
                break

            target_bin = uncovered[0]

            print(f"[HYBRID] Filling {target_bin}")

            item = generator.generate(target_bin)

            await self.start_item(item)
            await self.finish_item(item)

            budget.consume()

        print("[HYBRID] Gap filling finished.")

       # ==========================================================
    # Entry point
    # ==========================================================

    async def body(self):

        if self.use_ml:
            await self.run_ml_pool()
            await self.run_gap_fill()
        else:
            await self.run_baseline()