import os
import random
import pandas as pd

from pyuvm import uvm_sequence

from tb.sequences.sequence_item import (
    AXISeqItem,
    VALID_REGS,
    ADDR_CATEGORIES,
    random_invalid_addr,
    random_data_value,
)

from tb.components.env import (
   
    get_uncovered_bins,
    coverage_complete,
    TOTAL_BINS,
)


class AXISequence(uvm_sequence):
    """
    Hybrid AXI4-Lite sequence.

    Two modes:

    1. Baseline (use_hybrid=False)
       - Pure constrained-random generation.

    2. Hybrid mode (use_hybrid=True)
       - Replay clustered testcases generated by
         train_model.py + cluster_tests.py.
    """

    def __init__(
        self,
        name="AXISequence",
        total_budget=300,
        use_hybrid=False,
    ):
        super().__init__(name)

        self.total_budget = total_budget
        self.use_hybrid = use_hybrid

        # Shared execution counter across both phases
        self.executed = 0

    # ==========================================================
    # Baseline generation
    # ==========================================================

    async def run_baseline(self):

        print(f"[BASELINE MODE] Running {self.total_budget} random tests")

        for _ in range(self.total_budget):

            item = AXISeqItem("item")
            item.randomize()

            await self.start_item(item)
            await self.finish_item(item)

            self.executed += 1

    # ==========================================================
    # ML replay mode
    # ==========================================================

    async def run_ml_pool(self):
        """
        Replay clustered testcases from clustered_tests.csv.
        """

        base_dir = os.path.dirname(__file__)

        csv_path = os.path.join(
            base_dir,
            "../../ml/clustered_tests.csv",
        )

        df = pd.read_csv(csv_path)

        remaining_budget = self.total_budget - self.executed

        tests_to_run = min(
            len(df),
            remaining_budget,
        )

        print(f"[HYBRID MODE] Running {tests_to_run} clustered testcases")

        reverse_txn_map = {
            0: "WRITE",
            1: "READ",
        }

        reverse_addr_map = {
            0: "REG0",
            1: "REG1",
            2: "REG2",
            3: "REG3",
            4: "INVALID",
        }

        reverse_data_map = {
            0: "ZERO",
            1: "SMALL",
            2: "LARGE",
            3: "NA",
        }

        for _, row in df.head(tests_to_run).iterrows():

            if self.executed >= self.total_budget:
                break

            if coverage_complete():
                break

            txn_type = reverse_txn_map[int(row["txn_type"])]
            addr_cat = reverse_addr_map[int(row["addr_category"])]
            data_label = reverse_data_map[int(row["data_type"])]

            item = AXISeqItem("item")

            item.txn_type = txn_type

            # -----------------------------
            # Address
            # -----------------------------
            if addr_cat == "INVALID":
                item.addr = random_invalid_addr()
            else:
                item.addr = VALID_REGS[
                    ADDR_CATEGORIES.index(addr_cat)
                ]

            # -----------------------------
            # Data
            # -----------------------------
            if txn_type == "WRITE":

                if addr_cat == "INVALID":

                    item.data_type = "NA"
                    item.wdata = random.randint(
                        0,
                        0xFFFFFFFF,
                    )

                else:

                    item.data_type = data_label

                    item.wdata = random_data_value(
                        data_label
                    )

            else:
                item.data_type = "NA"
                item.wdata = 0

            await self.start_item(item)
            await self.finish_item(item)

            self.executed += 1

        print(
            f"[HYBRID MODE] Replay complete "
            f"({self.executed}/{self.total_budget})"
        )
    def generate_directed_item(self, target_bin):

        item = AXISeqItem("directed_item")

        if target_bin[0] == "READ":

            item.txn_type = "READ"

            addr_cat = target_bin[1]

            if addr_cat == "INVALID":
                item.addr = random_invalid_addr()
            else:
                item.addr = VALID_REGS[
                    ADDR_CATEGORIES.index(addr_cat)
                ]

            item.wdata = 0
            item.data_type = "NA"

            return item

        # WRITE

        item.txn_type = "WRITE"

        addr_cat = target_bin[1]

        if addr_cat == "INVALID":

            item.addr = random_invalid_addr()
            item.wdata = random_data_value("LARGE")
            item.data_type = "NA"

            return item

        item.addr = VALID_REGS[
            ADDR_CATEGORIES.index(addr_cat)
        ]

        data_type = target_bin[2]

        item.data_type = data_type
        item.wdata = random_data_value(data_type)

        return item

    # ==========================================================
    # Hybrid Gap Filling
    # ==========================================================

    async def run_gap_fill(self):
        """
        Execute deterministic directed transactions for all
        uncovered coverage bins until coverage is complete or
        the execution budget is exhausted.
        """

        print("[HYBRID] Starting deterministic gap filling...")

        while True:

            if coverage_complete():
                print("[HYBRID] Functional coverage complete.")
                break

            if self.executed >= self.total_budget:
                print("[HYBRID] Execution budget exhausted.")
                break

            uncovered = list(get_uncovered_bins())

            if not uncovered:
                print("[HYBRID] No uncovered bins remain.")
                break

            target_bin = uncovered[0]

            print(f"[HYBRID] Filling {target_bin}")

            item = self.generate_directed_item(target_bin)

            await self.start_item(item)
            await self.finish_item(item)

            self.executed += 1

        print(
            f"[HYBRID] Gap filling finished "
            f"({self.executed}/{self.total_budget})"
        )

    # ==========================================================
    # Entry point
    # ==========================================================

    async def body(self):

        if self.use_hybrid:
            await self.run_ml_pool()
            await self.run_gap_fill()
        else:
            await self.run_baseline()